networks:
    ca_network:
        driver: bridge
    ipvlan:
        external: true
        name: ipvlan_network
secrets:
    password:
        file: $PASSWORD_FILE
    provisioner_password:
        file: $PROVISIONER_PASSWORD_FILE
services:
    ca:
        image: smallstep/step-ca:latest
        environment:
            STEPPATH: $CA_STEPPATH
            DOCKER_STEPCA_INIT_NAME: $CA_DOCKER_STEPCA_INIT_NAME
            DOCKER_STEPCA_INIT_DNS_NAMES: ca
            DOCKER_STEPCA_INIT_ADDRESS: :5739
        volumes:
            - ./src:$CA_STEPPATH
        networks:
            - ca_network
        restart: unless-stopped
    crt:
        image: dqio/crtpatch:latest
        environment:
            STEP_INIT_NAME: $CRT_STEP_INIT_NAME
            STEP_INIT_DNS: $CRT_STEP_INIT_DNS
            STEP_CA_URL: $CRT_STEP_CA_URL
            STEP_FINGERPRINT: $CRT_STEP_FINGERPRINT
            STEP_KID: $CRT_STEP_KID
            STEP_RENEW_PERIOD: $CRT_STEP_RENEW_PERIOD
            STEP_PASSWORD_FILE: /run/secrets/password
            STEP_PROVISIONER_PASSWORD_FILE: /run/secrets/provisioner_password
        volumes:
            - ./tmp:/var/local/step
        secrets:
            - password
            - provisioner_password
        networks:
            - ca_network
        depends_on:
            - ca
        restart: unless-stopped

