networks:
    ca_network:
        driver: bridge
services:
    ca:
        image: smallstep/step-ca:latest
        environment:
            STEPPATH: $CA_STEPPATH
            DOCKER_STEPCA_INIT_NAME: $CA_DOCKER_STEPCA_INIT_NAME
            DOCKER_STEPCA_INIT_DNS_NAMES: $CA_DOCKER_STEPCA_INIT_DNS_NAMES
            DOCKER_STEPCA_INIT_ADDRESS: $CA_DOCKER_STEPCA_INIT_ADDRESS
        volumes:
            - ./src:$CA_STEPPATH
        networks:
            - ca_network
        restart: unless-stopped

